# Generated by Django 3.2 on 2021-04-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0004_kategori_keterangan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buku',
            old_name='kelompok_id',
            new_name='kategori_id',
        ),
        migrations.AlterField(
            model_name='kategori',
            name='keterangan',
            field=models.TextField(),
        ),
    ]
